[tool.poetry]
name = "urjson-decimal"
version = "0.1.0"
description = "orjson with decimal support"
authors = [
    "Reynaldo Gil <gilcu2@gmail.com>",
]

[tool.poetry.dependencies]
python = ">=3.9.0, <4.0.0"
arrow = "^1.2.3"
faker = "^18.11.2"
numpy = "^1.25.0"
pendulum = "^2.1.2"
psutil = "^5.9.5"
pytest = "^7.4.0"
pytz = "^2023.3"



[project]
repository = "https://github.com/ijl/orjson"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Typing :: Typed",
]

[project.urls]
Changelog = "https://github.com/ijl/orjson/blob/master/CHANGELOG.md"

[build-system]
build-backend = "maturin"
requires = ["maturin>=1,<2"]

[tool.maturin]
python-source = "pysrc"
include = [
    { format = "sdist", path = ".cargo/*" },
    { format = "sdist", path = "build.rs" },
    { format = "sdist", path = "Cargo.lock" },
    { format = "sdist", path = "include/**/*" },
]


[tool.black]
line-length = 88
target-version = ["py37"]
include = ".pyi?$"

[tool.ruff]
line-length = 88
target-version = "py37"

ignore = [
    "E501", # line too long
    "F601", # Dictionary key literal ... repeated
]

[tool.mypy]
python_version = "3.8" # numpy
